### PR TITLE
Add DNF and rpm-ostree support #3

### PR DESCRIPTION
**Pull request by LyesSaadi**
Adding a support for the main rpm based package managers.

Note: I did not test this yet.
Note 2: Is the "update" field for updating repository metadata or for updating packages?

### CODE REVIEW

**Review by MatthewScholefield — APPROVED** [review]
Thanks for the contribution! The update field is just for updating metadata so I think what you put looks fine.

As a first time contributor, Mycroft normally asks to submit a CLA here:
https://mycroft.ai/cla/

Anyways, otherwise everything looks good.

**Comment by LyesSaadi** [comment]
> Thanks for the contribution! The update field is just for updating metadata so I think what you put looks fine.

I can confirm: when seeing the apt-get update, I assumed it was for updating metadata!

> As a first time contributor, Mycroft normally asks to submit a CLA here:
> https://mycroft.ai/cla/

I've completed the form, I'm now waiting for an answer!

> Anyways, otherwise everything looks good.

**Comment by LyesSaadi** [comment]
I did not add an order for the package managers, I let you guys figure that out, but I just wanted to say that I recommend adding rpm-ostree before dnf, as it is a very specific package manager that will only work on [Fedora Silverblue/CoreOS](https://docs.fedoraproject.org/en-US/fedora-silverblue/), and is also the only package manager that will work on those, any other one (except flatpak) will fail due to the specific nature of that OS.

**Comment by MatthewScholefield** [comment]
Sure, might as well add that explicitly higher than dnf in the order then.

**Comment by LyesSaadi** [comment]
Hi! So, I just signed the CLA!

**Comment by krisgesling** [comment]
CLA confirmed, thanks!

Did you want to switch the order of the managers before we merge?

**Comment by LyesSaadi** [comment]
I hope everything's good!

**Comment by krisgesling** [comment]
Yep, looks great. Merging.

Thanks Lyes!

**Pull request merged**
